name: Swift Lint and Build

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  
  lint:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install SwiftLint v0.40.3
      run: |
        curl -O https://github.com/realm/SwiftLint/releases/download/0.40.3/portable_swiftlint.zip
        unzip portable_swiftlint.zip portable
        mv portable/swiftlint ./swiftlint-custom
        rm -r portable
        rm portable_swiftlint.zip
      
    - name: Display the path
      run: ls -a
      shell: bash

    - name: Lint
      run: ./swiftlint-custom lint --config .swiftlint.yml --strict

#   build:
#     runs-on: macos-latest

#     steps:
#     - uses: actions/checkout@v2
    
#     - name: Build
#       run: xcodebuild clean build -project HackIllinois.xcodeproj -scheme HackIllinois -destination "platform=iOS Simulator,name=iPhone 11" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO -quiet
